// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVO-g0kRdOT6VslDFXWImNJx2wiKOcMwA',
    appId: '1:174739316241:web:5fead20fb9a4bd3c885bb0',
    messagingSenderId: '174739316241',
    projectId: 'first-project-1ebcd',
    authDomain: 'first-project-1ebcd.firebaseapp.com',
    storageBucket: 'first-project-1ebcd.firebasestorage.app',
    measurementId: 'G-9EZ9V61QRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrQTIj05F4FSkgXmCu6NSxhXlUM_fOd5U',
    appId: '1:174739316241:android:b13ce77427360531885bb0',
    messagingSenderId: '174739316241',
    projectId: 'first-project-1ebcd',
    storageBucket: 'first-project-1ebcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRdN1wYz0GMga27BdQByR0g112HGMo4nM',
    appId: '1:174739316241:ios:3cbb1b0247e5ecaf885bb0',
    messagingSenderId: '174739316241',
    projectId: 'first-project-1ebcd',
    storageBucket: 'first-project-1ebcd.firebasestorage.app',
    iosBundleId: 'com.example.assignment6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRdN1wYz0GMga27BdQByR0g112HGMo4nM',
    appId: '1:174739316241:ios:3cbb1b0247e5ecaf885bb0',
    messagingSenderId: '174739316241',
    projectId: 'first-project-1ebcd',
    storageBucket: 'first-project-1ebcd.firebasestorage.app',
    iosBundleId: 'com.example.assignment6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVO-g0kRdOT6VslDFXWImNJx2wiKOcMwA',
    appId: '1:174739316241:web:c567e26cbff4870d885bb0',
    messagingSenderId: '174739316241',
    projectId: 'first-project-1ebcd',
    authDomain: 'first-project-1ebcd.firebaseapp.com',
    storageBucket: 'first-project-1ebcd.firebasestorage.app',
    measurementId: 'G-14VBWS3TGZ',
  );
}
